"""
Created:   Dec 16, 2018
encoding:  UTF-8
Author:    Shuheng Liu
Contact:   wish1104@outlook.com
GitHub:    https://github.com/Johnny-Wish

(c) All Rights Reserved
License: https://choosealicense.com/licenses/gpl-3.0/

This package is created to test reflexive import, do not edit this file
"""
model_var = "This is a model variable"
param_var = "This is a param variable"


class LongVariableName:
    def __init__(self, x=0):
        self.x = x

    def __repr__(self):
        return "<{} Instance with x = {}>".format(self.__class__.__name__, self.x)

    def __str__(self):
        return self.__repr__()


some_long_variable_name = LongVariableName(123)

another_long_variable_name = LongVariableName(456)


def some_long_function_name(x):
    return x + 1
